### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by MilesChou**
Add Docker integration so that we can build the service easliy

### CODE REVIEW

**Comment by distler** [comment]
Out of curiosity, are you using this configuration? If so, what are you doing about database backups?

I ask because I am interested in improving the containerization of Instiki, and some insight from people actually using it via Docker would be helpful.

**Comment by MilesChou** [comment]
We can use volume mount setting to backup database when used SQLite. Here is an example command:

```
# prepare your sqlite file:

cd /path/to/your/host/dir
touch production.db.sqlite3

docker run -d -v /path/to/your/host/dir/production.db.sqlite3:/usr/src/app/db/production.db.sqlite3 instiki
```

And now the `production.db.sqlite3` will up-to-date when the application update.

Additionally, we can use the `docker cp` command to copy the sqlite file, just like `scp`. Here is an example:

```
docker run -d --name my-instiki instiki
docker cp my-instiki:/usr/src/app/db/production.db.sqlite3 /path/to/your/host/dir/
```

**Comment by distler** [comment]
It might be useful writing up some instructions, say [here](https://golem.ph.utexas.edu/wiki/instiki/show/Hosted+Services). Even if some steps are specific to your Docker-hosting provider, many things will be common.

Note: The [web service](https://github.com/distler/tex2svg) for the new Tikz figure support (new in Instiki 0.30.0) is also Dockerized, so you could run it alongside your Dockerized Instiki.

**Comment by MilesChou** [comment]
Another solution is [Docker Compose](https://docs.docker.com/compose/). It can compose many containers with a configuration written by YAML.

**Pull request merged**
