### PR TITLE
Atom feed for changes in XHTML diff form

### PR DESCRIPTION
**Pull request by jrblevin**
I added a new Changes Atom feed which includes XHTML diffs of each page revision. Previously, the Headlines and Full content feeds just showed the current state of each page, rather than the changes. Note that some feed readers may not style the differences properly because they strip out certain CSS styles (ideally, additions should be in green and removals should be in red with strikethrough text, just as on the web version).

### CODE REVIEW

**Comment by distler** [comment]
I'll take a look. But here are some quick comments/questions.

1. It would be helpful to have some tests for this new feature.
2. Inline styles are better-supported (in my limited experience) in feed readers than `<style>` elements.
3. How does this handle newly-created pages?

**Comment by jrblevin** [comment]
Thanks! Regarding your comments:

1. I added a second commit just now with some basic tests.
2. Indeed, the feed uses inline `style=` styles rather than a `<style>` element, but still certain feed readers strip some of the styles.
3. Since there is no previous revision to compare against, newly created pages simply appear in the feed unmodified. This is the standard behavior of `display_diff` on line 31 of `atom_changes.rxml`. The `revision.number > 1` conditionals on lines 13 and 28 determine how revised pages are handled relative to newly created pages. The revision number is appended to the title in the case of a revised page and in the case of a new page the "Added | Removed | Changed" legend at the top is omitted.

Take a look at the [Fortran Wiki](http://fortranwiki.org) if you want to see it in action. This patch scratches an itch I've had for a long time (not wanting to visit pages in a browser and click "See Changes" each time an edit shows up in the feed), but I fully understand if you'd rather not put it in the trunk given the limitations in item 2 above.

I don't know what fraction of feed readers strip simple styles like these. It's 1-1 in my case: Unread on iOS preserves them but ReadKit on OS X removes them.

**Comment by distler** [comment]
Aside from the duplicate hash keys in line 2 of  `app/views/wiki/atom_changes.rxml`, this looked good.

[Committed](https://github.com/parasew/instiki/commit/2819ffa05ce46de8042f8f8e2de2c7082ecaed07).

**Comment by jrblevin** [comment]
Nice catch on the hash keys. Actually, the mistake was that the last key should have been `'ins.diffmod'` instead of `'ins.diffins'`. It was a duplicate key, but with a different value. Overall the hash should be (with newlines for clarity):

```ruby
styles = {
  'del.diffdel' => 'background-color:#FAA; text-decoration:line-through;',
  'del.diffmod' => 'background-color:#FAA; text-decoration:line-through; border: 2px solid #FE0;',
  'ins.diffins' => 'background-color:#AFA; text-decoration:underline;',
  'ins.diffmod' => 'background-color:#AFA; text-decoration:underline; border: 2px solid #FE0;'
}
```

Sorry about that. I have updated my `feat/changes-atom` branch with [a patch](https://github.com/jrblevin/instiki/commit/dae7326779577a2cf3486c3c4dd9656a871f53f3) to fix this.

**Pull request closed without merging**
