### PR TITLE
Rails 3 updates

### PR DESCRIPTION
**Pull request by pond**
This is an attempt to create a Rails 3 compatible version of Instiki. Unfortunately, the diff is enormous because of a very large number of asset files that move into 'app/assets'. Asset pipeline compilation is unlikely to be viable for this application.

This work was made possible through the following invaluable resource:

* http://modelmoo.blogspot.co.nz/2013/03/migrating-instiki-to-rails-32.html

### CODE REVIEW

**Comment by pond** [comment]
Closing - this is not ready for consideration on the originating Instiki branch. Created in error there, instead of on my own fork as a way to marshal and track ongoing changes. Apologies for notification spam arising.

**Comment by pond** [comment]
Work will continue here:

* https://github.com/risc-os-open/instiki/pull/1

If I get it going (especially the tests) satisfactorily I'll most definitely submit the outcome back to here as a formal pull request.

**Comment by parasew** [comment]
i am suggesting we create different branches, so we can all continue working in this repository; so we can definitely have a rails3 and of course also a rails5 branch. i suggest for the rails5 version to re-design and restructure the project. i have more time in the coming months and i definitely want to discuss this in more detail. i will organize an irc-session where we can talk about this in more detail?

**Comment by distler** [comment]
I think a  rails3 branch would be really nice.

For the future, there are many very antiquated assumptions in the current code. It would be good to revisit some of those assumption if we choose to do a major re-write.

**Comment by pond** [comment]
Well you can see the progress at the branch on my fork. It finally came alive last night and a reasonable number of things are working but there are lots and lots of hurdles still. This is only part of the journey anyway - Rails 3 gets us to a minimum standard where Ruby 2.x is supported without a customised, vendor-locked Rails 2 packed with Instiki and that's great, but really we ought to be up at Rails 4.2 or even perhaps Rails 5 (thought that's maybe "a bit new"!).

**Comment by pond** [comment]
@parasew Sounds good. This is targeted at http://www.riscosopen.org/ so I've forked it as I'll end up doing work to integrate with our site template & CSS along with Hub for user management. Some of those changes are quite invasive and very custom so you wouldn't want them in the core code base. But I'm happy to move and continue the generic Rails 3 work on a branch within your repo, if you prefer?

**Comment by pond** [comment]
(Oh and IRC is fine except I'm in New Zealand so aligning timezones for IRC could be very difficult).

**Pull request closed without merging**
